# Generated by Django 5.1.2 on 2024-11-02 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_text', models.CharField(max_length=200, verbose_name='输入班级')),
            ],
            options={
                'verbose_name_plural': '班级管理',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_text', models.CharField(max_length=200)),
                ('info_text', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('是否启用', models.BooleanField(default=True)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.grade_class')),
            ],
            options={
                'verbose_name_plural': '学生名单',
            },
        ),
    ]
