# Generated by Django 5.1.2 on 2024-11-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.grade_class', verbose_name='所属班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='info_text',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_text',
            field=models.CharField(max_length=200, verbose_name='学生姓名'),
        ),
    ]
