# Generated by Django 5.1.2 on 2024-11-03 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_student_class_alter_student_info_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade_class',
            options={'verbose_name': '班级管理', 'verbose_name_plural': '班级管理'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生名单', 'verbose_name_plural': '学生名单'},
        ),
    ]
