# Generated by Django 5.1.2 on 2024-11-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_grade_class_options_alter_student_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Class',
            new_name='class_text',
        ),
    ]
