# Generated by Django 5.1.2 on 2024-11-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_rename_class_student_class_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade_class',
            name='student_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
