# Generated by Django 5.1.2 on 2024-11-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_grade_class_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade_class',
            name='student_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当前人数'),
        ),
    ]
