# Generated by Django 5.1.2 on 2024-11-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_alter_grade_class_student_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade_class',
            name='student_count',
        ),
        migrations.RemoveField(
            model_name='student',
            name='是否启用',
        ),
    ]
