# Generated by Django 5.1.2 on 2024-11-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_remove_grade_class_student_count_remove_student_是否启用'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade_class',
            name='student_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当前人数'),
        ),
    ]
