# Generated by Django 5.1.2 on 2024-11-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_grade_class_student_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade_class',
            name='student_count',
        ),
    ]
