# Generated by Django 5.1.2 on 2024-11-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_remove_grade_class_student_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade_class',
            name='student_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='当前人数'),
        ),
    ]
