# Generated by Django 5.1.2 on 2024-11-12 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_grade_class_student_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
            ],
        ),
    ]
