# Generated by Django 5.1.2 on 2024-11-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_checkeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkeddata',
            name='check_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
